### ISSUE TITLE
podBindingDeployment.yaml has some wrong indentation 

### ISSUE THREAD

**Issue by iamNoah1** [MicrosoftDocs/azure-docs.de-de#720]
[Hier Feedback eingeben]

In podBindingDeployment.yaml the volumes section is described as: 

```
volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname
          nodePublishSecretRef:
              name: secrets-store-creds
```

where it should be: 

```
volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname
        nodePublishSecretRef:
          name: secrets-store-creds
```

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: eee999c1-32dd-d014-40df-8027adee1258
* Version Independent ID: 19a29c09-79f8-580a-841f-873e2801da56
* Content: [Integrieren von Azure Key Vault mit Kubernetes](https://docs.microsoft.com/de-de/azure/key-vault/general/key-vault-integrate-kubernetes)
* Content Source: [articles/key-vault/general/key-vault-integrate-kubernetes.md](https://github.com/MicrosoftDocs/azure-docs.de-de/blob/master/articles/key-vault/general/key-vault-integrate-kubernetes.md)
* Service: **key-vault**
* GitHub Login: @ShaneBala-keyvault
* Microsoft Alias: **sudbalas**
